# Creating Dataframe by Scrapping Wikipedia

In [27]:
import pandas as pd
import requests

In [26]:
#downloading csv
!wget -q -O 'Geospatial_data.csv' http://cocl.us/Geospatial_data
print('Data downloaded!')

Data downloaded!

In [29]:
df1= pd.read_csv('Geospatial_data.csv')
df1.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [30]:
df2 = pd.read_csv('Main_CSV.csv')

In [31]:
df = pd.merge(df2, df1, left_on='PostalCode', right_on='Postal Code')
df.head()

,Unnamed: 0,PostalCode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
0,2,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
1,3,M4A,North York,Victoria Village,M4A,43.725882,-79.315572
2,4,M5A,Downtown Toronto,Harbourfront,M5A,43.654260,-79.360636
3,5,M5A,Downtown Toronto,Regent Park,M5A,43.654260,-79.360636
4,6,M6A,North York,Lawrence Heights,M6A,43.718518,-79.464763

In [32]:
df=df.drop(['Postal Code'], axis=1)
df.head(20)

,Unnamed: 0,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,2,M3A,North York,Parkwoods,43.753259,-79.329656
1,3,M4A,North York,Victoria Village,43.725882,-79.315572
2,4,M5A,Downtown Toronto,Harbourfront,43.654260,-79.360636
3,5,M5A,Downtown Toronto,Regent Park,43.654260,-79.360636
4,6,M6A,North York,Lawrence Heights,43.718518,-79.464763
5,7,M6A,North York,Lawrence Manor,43.718518,-79.464763
6,8,M7A,Queen's Park,Not assigned,43.662301,-79.389494
7,10,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
8,11,M1B,Scarborough,Rouge,43.806686,-79.194353
9,12,M1B,Scarborough,Malvern,43.806686,-79.194353
10,14,M3B,North York,Don Mills North,43.745906,-79.352188
11,15,M4B,East York,Woodbine Gardens,43.706397,-79.309937
12,16,M4B,East York,Parkview Hill,43.706397,-79.309937
13,17,M5B,Downtown Toronto,Ryerson,43.657162,-79.378937
14,18,M5B,Downtown Toronto,Garden District,43.657162,-79.378937
15,19,M6B,North York,Glencairn,43.709577,-79.445073
16,22,M9B,Etobicoke,Cloverdale,43.650943,-79.554724
17,23,M9B,Etobicoke,Islington,43.650943,-79.554724
18,24,M9B,Etobicoke,Martin Grove,43.650943,-79.554724
19,25,M9B,Etobicoke,Princess Gardens,43.650943,-79.554724

In [34]:
df.shape

(212, 6)